# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = 'bento/centos-6.9'

  config.vbguest.auto_update = false
  config.omnibus.chef_version = "12.19.36"

  config.vm.define "lab2" do |lab2|
    lab2.vm.hostname = 'lab2.local'
    lab2.vm.provision 'chef_solo' do |chef|
      # chef.add_recipe 'my_cbk'
      chef.nodes_path = './.vagrant/nodes'
    end
  end
end
